Repository Team-SilverTown/Team-SilverTown-MasilGasil-BE, pull requests merged in 2024-02, with the labels that each got.

#12 🚀 ci 파이프라인 생성
  .github/workflows/ci-pipeline.yml
Labels: ✅  Feature, 💣 전시 상황!!!

#13 🚀 Github CODEOWNERS 설정
  .github/workflows/CODEOWNERS
Labels: 🐕🐕🐕 진도개 셋!, ✅  Feature

#17 🚀 에러 코드 포함 예외 구조화
  src/main/java/team/silvertown/masil/common/exception/BadRequestException.java
  src/main/java/team/silvertown/masil/common/exception/BaseException.java
  src/main/java/team/silvertown/masil/common/exception/DataNotFoundException.java
  src/main/java/team/silvertown/masil/common/exception/DuplicateResourceException.java
  src/main/java/team/silvertown/masil/common/exception/ErrorCode.java
  src/main/java/team/silvertown/masil/common/exception/ErrorResponse.java
  src/main/java/team/silvertown/masil/common/exception/ForbiddenException.java
  src/main/java/team/silvertown/masil/common/exception/GlobalExceptionHandler.java
Labels: 🐕🐕🐕 진도개 셋!, ✅  Feature

#14 🚀 Checkstyle 적용
  build.gradle
  config/checkstyle/checkstyle.xml
  config/checkstyle/suppressions.xml
Labels: 🐕🐕🐕 진도개 셋!, ✅  Feature

#15 🚀 스키마 엔티티 작성
  build.gradle
  src/main/java/team/silvertown/masil/common/BaseEntity.java
  src/main/java/team/silvertown/masil/common/map/Address.java
  src/main/java/team/silvertown/masil/common/map/KakaoPoint.java
  src/main/java/team/silvertown/masil/common/map/KakaoPointMapper.java
  src/main/java/team/silvertown/masil/config/WebSecurityConfig.java
  src/main/java/team/silvertown/masil/masil/domain/Masil.java
  src/main/java/team/silvertown/masil/masil/domain/MasilPin.java
  src/main/java/team/silvertown/masil/post/domain/Post.java
  src/main/java/team/silvertown/masil/post/domain/PostPin.java
  src/main/java/team/silvertown/masil/user/domain/Authority.java
  src/main/java/team/silvertown/masil/user/domain/ExerciseIntensity.java
  src/main/java/team/silvertown/masil/user/domain/Provider.java
  src/main/java/team/silvertown/masil/user/domain/Sex.java
  src/main/java/team/silvertown/masil/user/domain/User.java
  src/main/java/team/silvertown/masil/user/domain/UserAuthority.java
  src/main/resources/db/migration/V1__schema.sql
  src/test/java/team/silvertown/masil/masil/domain/MasilPinTest.java
  src/test/java/team/silvertown/masil/masil/domain/MasilTest.java
  src/test/java/team/silvertown/masil/post/domain/PostPinTest.java
  src/test/java/team/silvertown/masil/post/domain/PostTest.java
  src/test/java/team/silvertown/masil/user/domain/UserAuthorityTest.java
  src/test/java/team/silvertown/masil/user/domain/UserTest.java
Labels: ✅  Feature, 💣 전시 상황!!!

#18 ⚙️ github CODEOWNERS 파일 경로 수정
  .github/CODEOWNERS
Labels: ⚙️ Refactoring, 🐕🐕🐕 진도개 셋!

#19 🚀 공통 validator 추가
  src/main/java/team/silvertown/masil/common/Validator.java
Labels: ✅  Feature, 💣 전시 상황!!!

#20 🔨 validator 접근 제어자 변경
  src/main/java/team/silvertown/masil/common/validator/Validator.java
Labels: ⚙️ Refactoring

#23 🚀 마실 도메인 생성 로직 및 검증 추가
  build.gradle
  src/main/java/team/silvertown/masil/common/map/Address.java
  src/main/java/team/silvertown/masil/common/map/KakaoPointMapper.java
  src/main/java/team/silvertown/masil/common/map/MapErrorCode.java
  src/main/java/team/silvertown/masil/common/validator/Validator.java
  src/main/java/team/silvertown/masil/masil/domain/Masil.java
  src/main/java/team/silvertown/masil/masil/domain/MasilPin.java
  src/main/java/team/silvertown/masil/masil/domain/MasilTitle.java
  src/main/java/team/silvertown/masil/masil/exception/MasilErrorCode.java
  src/main/java/team/silvertown/masil/masil/validator/MasilValidator.java
  src/main/resources/db/migration/V1__schema.sql
  src/test/java/team/silvertown/masil/common/map/AddressTest.java
  src/test/java/team/silvertown/masil/common/map/KakaoPointMapperTest.java
  src/test/java/team/silvertown/masil/masil/domain/MasilPinTest.java
  src/test/java/team/silvertown/masil/masil/domain/MasilTest.java
  src/test/java/team/silvertown/masil/masil/domain/MasilTitleTest.java
Labels: 🐕 진도개 하나!, ✅ Feature

#27 🚀 로컬 환경 SQL 쿼리 로깅
  src/main/resources/application-local.yml
Labels: 🐕🐕🐕 진도개 셋!, ✅ Feature

#26 🚀 마실 생성 API 구현
  src/main/java/team/silvertown/masil/common/exception/GlobalExceptionHandler.java
  src/main/java/team/silvertown/masil/masil/controller/MasilController.java
  src/main/java/team/silvertown/masil/masil/dto/CreatePinRequest.java
  src/main/java/team/silvertown/masil/masil/dto/CreateRequest.java
  src/main/java/team/silvertown/masil/masil/dto/CreateResponse.java
  src/main/java/team/silvertown/masil/masil/repository/MasilPinRepository.java
  src/main/java/team/silvertown/masil/masil/repository/MasilRepository.java
  src/main/java/team/silvertown/masil/masil/service/MasilService.java
  src/main/java/team/silvertown/masil/user/repository/UserRepository.java
  src/test/java/team/silvertown/masil/masil/service/MasilServiceTest.java
Labels: 🐕🐕🐕 진도개 셋!, ✅ Feature

#36 🚀 JPA 관찰용 디버그 로깅 추가
  src/main/resources/application-local.yml
Labels: 🐕🐕🐕 진도개 셋!, ✅ Feature

#35 🚀 마실 단일 조회 API 구현
  src/main/java/team/silvertown/masil/common/map/KakaoPoint.java
  src/main/java/team/silvertown/masil/masil/controller/MasilController.java
  src/main/java/team/silvertown/masil/masil/domain/Masil.java
  src/main/java/team/silvertown/masil/masil/domain/MasilPin.java
  src/main/java/team/silvertown/masil/masil/dto/MasilResponse.java
  src/main/java/team/silvertown/masil/masil/dto/PinResponse.java
  src/main/java/team/silvertown/masil/masil/exception/MasilErrorCode.java
  src/main/java/team/silvertown/masil/masil/service/MasilService.java
  src/main/java/team/silvertown/masil/masil/validator/MasilValidator.java
  src/test/java/team/silvertown/masil/masil/domain/MasilPinTest.java
  src/test/java/team/silvertown/masil/masil/service/MasilServiceTest.java
  src/test/java/team/silvertown/masil/texture/BaseDomainTexture.java
  src/test/java/team/silvertown/masil/texture/MasilTexture.java
Labels: 🐕🐕 진도개 둘!, ✅ Feature

#30 🚀 소셜 로그인 (kakao login + jwt token) 구현
  .gitignore
  build.gradle
  src/main/java/team/silvertown/masil/MasilApplication.java
  src/main/java/team/silvertown/masil/config/WebSecurityConfig.java
  src/main/java/team/silvertown/masil/config/jwt/JwtAuthenticationFilter.java
  src/main/java/team/silvertown/masil/config/jwt/JwtProperties.java
  src/main/java/team/silvertown/masil/config/jwt/JwtTokenProvider.java
  src/main/java/team/silvertown/masil/config/oauth2/OAuth2AuthenticationSuccessHandler.java
  src/main/java/team/silvertown/masil/config/security/CustomAuthenticationEntryPoint.java
  src/main/java/team/silvertown/masil/config/security/HttpRequestsConfigurer.java
  src/main/java/team/silvertown/masil/config/security/WebSecurityConfig.java
  src/main/java/team/silvertown/masil/security/exception/InvalidAuthenticationException.java
  src/main/java/team/silvertown/masil/security/exception/OAuthValidator.java
  src/main/java/team/silvertown/masil/user/domain/Provider.java
  src/main/java/team/silvertown/masil/user/domain/UserAuthority.java
  src/main/java/team/silvertown/masil/user/dto/LoginResponseDto.java
  src/main/java/team/silvertown/masil/user/exception/UserErrorCode.java
  src/main/java/team/silvertown/masil/user/exception/UserValidator.java
  src/main/java/team/silvertown/masil/user/repository/UserAuthorityRepository.java
  src/main/java/team/silvertown/masil/user/repository/UserRepository.java
  src/main/java/team/silvertown/masil/user/service/UserService.java
  src/main/java/team/silvertown/masil/user/util/CustomUserArgumentResolver.java
  src/main/java/team/silvertown/masil/user/util/LoginUser.java
  src/main/resources/application.yml
  src/test/java/team/silvertown/masil/config/jwt/JwtTokenProviderTest.java
  src/test/java/team/silvertown/masil/masil/service/MasilServiceTest.java
  src/test/java/team/silvertown/masil/testConfig/JwtTestConfig.java
  src/test/java/team/silvertown/masil/testConfig/OAuth2TestConfig.java
  src/test/java/team/silvertown/masil/user/domain/ProviderTest.java
  src/test/java/team/silvertown/masil/user/domain/UserAuthorityTest.java
  src/test/java/team/silvertown/masil/user/service/UserServiceTest.java
Labels: 🐕 진도개 하나!, ✅ Feature
