Repository Team-SilverTown/Team-SilverTown-MasilGasil-BE, pull requests merged in 2024-03, with the labels that each got.

#39 🚀 user nickname 중복 체크 api 작성
  src/main/java/team/silvertown/masil/user/controller/UserController.java
  src/main/java/team/silvertown/masil/user/exception/UserErrorCode.java
  src/main/java/team/silvertown/masil/user/repository/UserRepository.java
  src/main/java/team/silvertown/masil/user/service/UserService.java
  src/test/java/team/silvertown/masil/user/service/UserServiceTest.java
Labels: 🐕🐕🐕 진도개 셋!, ✅ Feature

#47 🚀 스웨거 추가
  build.gradle
  src/main/java/team/silvertown/masil/config/SwaggerConfig.java
  src/main/java/team/silvertown/masil/masil/controller/MasilController.java
  src/main/resources/application.yml
Labels: ✅ Feature, 💣 전시 상황!!!

#40 🚀 최근 마실 조회 API
  .gitignore
  build.gradle
  src/main/java/team/silvertown/masil/common/response/SliceResponse.java
  src/main/java/team/silvertown/masil/masil/controller/MasilController.java
  src/main/java/team/silvertown/masil/masil/dto/RecentMasilResponse.java
  src/main/java/team/silvertown/masil/masil/dto/SimpleMasilResponse.java
  src/main/java/team/silvertown/masil/masil/repository/MasilQueryRepository.java
  src/main/java/team/silvertown/masil/masil/repository/MasilQueryRepositoryImpl.java
  src/main/java/team/silvertown/masil/masil/repository/MasilRepository.java
  src/main/java/team/silvertown/masil/masil/service/MasilService.java
  src/main/java/team/silvertown/masil/user/controller/UserController.java
  src/test/java/team/silvertown/masil/masil/service/MasilServiceTest.java
Labels: ✅ Feature, 💣 전시 상황!!!

#44 🚀 기간 별 마실 조회 API 구현
  src/main/java/team/silvertown/masil/common/util/DateTimeConverter.java
  src/main/java/team/silvertown/masil/config/QueryDslConfig.java
  src/main/java/team/silvertown/masil/masil/controller/MasilController.java
  src/main/java/team/silvertown/masil/masil/dto/CreateResponse.java
  src/main/java/team/silvertown/masil/masil/dto/MasilDailyDetailDto.java
  src/main/java/team/silvertown/masil/masil/dto/MasilDailyDto.java
  src/main/java/team/silvertown/masil/masil/dto/request/CreatePinRequest.java
  src/main/java/team/silvertown/masil/masil/dto/request/CreateRequest.java
  src/main/java/team/silvertown/masil/masil/dto/request/PeriodRequest.java
  src/main/java/team/silvertown/masil/masil/dto/response/CreateResponse.java
  src/main/java/team/silvertown/masil/masil/dto/response/MasilResponse.java
  src/main/java/team/silvertown/masil/masil/dto/response/PeriodResponse.java
  src/main/java/team/silvertown/masil/masil/dto/response/PinResponse.java
  src/main/java/team/silvertown/masil/masil/dto/response/RecentMasilResponse.java
  src/main/java/team/silvertown/masil/masil/dto/response/SimpleMasilResponse.java
  src/main/java/team/silvertown/masil/masil/repository/MasilQueryRepository.java
  src/main/java/team/silvertown/masil/masil/repository/MasilQueryRepositoryImpl.java
  src/main/java/team/silvertown/masil/masil/service/MasilService.java
  src/test/java/team/silvertown/masil/alias/H2Alias.java
  src/test/java/team/silvertown/masil/masil/service/MasilServiceTest.java
  src/test/java/team/silvertown/masil/texture/MasilTexture.java
Labels: ✅ Feature, 💣 전시 상황!!!

#49 🚀 사용자 추가 정보 API
  src/main/java/team/silvertown/masil/common/map/KakaoPoint.java
  src/main/java/team/silvertown/masil/common/validator/DateValidator.java
  src/main/java/team/silvertown/masil/config/jwt/JwtAuthenticationFilter.java
  src/main/java/team/silvertown/masil/config/jwt/JwtTokenProvider.java
  src/main/java/team/silvertown/masil/config/oauth2/OAuth2AuthenticationSuccessHandler.java
  src/main/java/team/silvertown/masil/config/security/HttpRequestsConfigurer.java
  src/main/java/team/silvertown/masil/config/security/WebSecurityConfig.java
  src/main/java/team/silvertown/masil/masil/domain/Masil.java
  src/main/java/team/silvertown/masil/security/exception/OAuthValidator.java
  src/main/java/team/silvertown/masil/user/controller/UserController.java
  src/main/java/team/silvertown/masil/user/domain/ExerciseIntensity.java
  src/main/java/team/silvertown/masil/user/domain/Sex.java
  src/main/java/team/silvertown/masil/user/domain/User.java
  src/main/java/team/silvertown/masil/user/domain/UserAgreement.java
  src/main/java/team/silvertown/masil/user/dto/OnboardRequest.java
  src/main/java/team/silvertown/masil/user/exception/UserErrorCode.java
  src/main/java/team/silvertown/masil/user/exception/UserValidator.java
  src/main/java/team/silvertown/masil/user/repository/UserAgreementRepository.java
  src/main/java/team/silvertown/masil/user/repository/UserAuthorityRepository.java
  src/main/java/team/silvertown/masil/user/service/UserService.java
  src/main/java/team/silvertown/masil/user/validator/UserValidator.java
  src/main/resources/db/migration/V2__schema.sql
  src/test/java/team/silvertown/masil/texture/MapTexture.java
  src/test/java/team/silvertown/masil/texture/UserTexture.java
  src/test/java/team/silvertown/masil/user/domain/ProviderTest.java
  src/test/java/team/silvertown/masil/user/dto/OnboardRequestTest.java
  src/test/java/team/silvertown/masil/user/service/UserServiceTest.java
Labels: ✅ Feature

#64 🚀 로그인 방식 수정
  build.gradle
  src/main/java/team/silvertown/masil/common/validator/DateValidator.java
  src/main/java/team/silvertown/masil/config/oauth2/OAuth2AuthenticationSuccessHandler.java
  src/main/java/team/silvertown/masil/config/security/HttpRequestsConfigurer.java
  src/main/java/team/silvertown/masil/config/security/WebSecurityConfig.java
  src/main/java/team/silvertown/masil/masil/domain/Masil.java
  src/main/java/team/silvertown/masil/security/exception/OAuthValidator.java
  src/main/java/team/silvertown/masil/user/controller/UserController.java
  src/main/java/team/silvertown/masil/user/domain/ExerciseIntensity.java
  src/main/java/team/silvertown/masil/user/dto/KakaoResponse.java
  src/main/java/team/silvertown/masil/user/dto/LoginRequest.java
  src/main/java/team/silvertown/masil/user/dto/LoginResponse.java
  src/main/java/team/silvertown/masil/user/dto/OAuthResponse.java
  src/main/java/team/silvertown/masil/user/exception/UserErrorCode.java
  src/main/java/team/silvertown/masil/user/exception/UserValidator.java
  src/main/java/team/silvertown/masil/user/repository/UserRepository.java
  src/main/java/team/silvertown/masil/user/service/KakaoOAuthService.java
  src/main/java/team/silvertown/masil/user/service/OAuthService.java
  src/main/java/team/silvertown/masil/user/service/UserService.java
  src/main/java/team/silvertown/masil/user/service/restTemplate/RestTemplateService.java
  src/main/java/team/silvertown/masil/user/util/RestTemplateConfig.java
  src/main/resources/application.yml
  src/test/java/team/silvertown/masil/config/jwt/JwtTokenProviderTest.java
  src/test/java/team/silvertown/masil/user/dto/OnboardRequestTest.java
  src/test/java/team/silvertown/masil/user/service/KakaoOAuthServiceTest.java
  src/test/java/team/silvertown/masil/user/service/UserServiceTest.java
  src/test/java/team/silvertown/masil/user/service/restTemplate/RestTemplateServiceTest.java
Labels: ⚙️ Refactoring, 🐕 진도개 하나!

#62 🚀 로컬 환경 CORS 설정 추가
  src/main/java/team/silvertown/masil/config/WebMvcConfig.java
Labels: ✅ Feature

#66 🚀 내 정보를 조회하는 me api 작성
  src/main/java/team/silvertown/masil/config/security/HttpRequestsConfigurer.java
  src/main/java/team/silvertown/masil/user/controller/UserController.java
  src/main/java/team/silvertown/masil/user/domain/User.java
  src/main/java/team/silvertown/masil/user/dto/MeInfoResponse.java
  src/main/java/team/silvertown/masil/user/service/UserService.java
  src/main/resources/db/migration/V1__schema.sql
  src/test/java/team/silvertown/masil/user/service/UserServiceTest.java
Labels: ✅ Feature

#46 🚀 이미지 업로드 기능 구현
  .github/workflows/ci-pipeline.yml
  .gitignore
  aws/Dockerfile
  aws/init-aws.sh
  aws/policy.json
  build.gradle
  docker-compose.yml
  src/main/java/team/silvertown/masil/image/config/S3Properties.java
  src/main/java/team/silvertown/masil/image/controller/ImageController.java
  src/main/java/team/silvertown/masil/image/dto/ImageResponse.java
  src/main/java/team/silvertown/masil/image/exception/ImageErrorCode.java
  src/main/java/team/silvertown/masil/image/service/ImageService.java
  src/main/java/team/silvertown/masil/image/validator/ImageFile.java
  src/main/java/team/silvertown/masil/image/validator/ImageFileType.java
  src/main/java/team/silvertown/masil/image/validator/ImageFileValidator.java
  src/main/resources/application.yml
  src/test/java/team/silvertown/masil/image/service/ImageServiceTest.java
  src/test/java/team/silvertown/masil/test/LocalstackTest.java
Labels: 🐕 진도개 하나!, ✅ Feature

#51 🚀 산책로 포스트 및 포스트 핀 도메인 생성 로직 추가
  src/main/java/team/silvertown/masil/masil/exception/MasilErrorCode.java
  src/main/java/team/silvertown/masil/post/domain/Post.java
  src/main/java/team/silvertown/masil/post/domain/PostPin.java
  src/main/java/team/silvertown/masil/post/exception/PostErrorCode.java
  src/main/java/team/silvertown/masil/post/validator/PostValidator.java
  src/test/java/team/silvertown/masil/post/domain/PostPinTest.java
  src/test/java/team/silvertown/masil/post/domain/PostTest.java
  src/test/java/team/silvertown/masil/texture/PostTexture.java
Labels: 🐕 진도개 하나!, ✅ Feature

#73 ⚒️ user me api 요청 시 분기처리를 원할하게 처리
  src/main/java/team/silvertown/masil/config/security/HttpRequestsConfigurer.java
  src/main/java/team/silvertown/masil/user/validator/UserValidator.java
  src/test/java/team/silvertown/masil/user/dto/OnboardRequestTest.java
Labels: 🔥 Hot fix, ⚙️ Refactoring, 🐛 Bug, 💣 전시 상황!!!

#52 🚀 산책로 포스트 생성 API 구현
  src/main/java/team/silvertown/masil/masil/dto/request/CreateRequest.java
  src/main/java/team/silvertown/masil/masil/service/MasilService.java
  src/main/java/team/silvertown/masil/post/controller/PostController.java
  src/main/java/team/silvertown/masil/post/domain/Post.java
  src/main/java/team/silvertown/masil/post/dto/request/CreatePinRequest.java
  src/main/java/team/silvertown/masil/post/dto/request/CreateRequest.java
  src/main/java/team/silvertown/masil/post/dto/response/CreateResponse.java
  src/main/java/team/silvertown/masil/post/exception/PostErrorCode.java
  src/main/java/team/silvertown/masil/post/repository/PostPinRepository.java
  src/main/java/team/silvertown/masil/post/repository/PostRepository.java
  src/main/java/team/silvertown/masil/post/service/PostService.java
  src/main/java/team/silvertown/masil/post/validator/PostValidator.java
  src/test/java/team/silvertown/masil/post/domain/PostTest.java
  src/test/java/team/silvertown/masil/post/service/PostServiceTest.java
Labels: 🐕 진도개 하나!, ✅ Feature

#54 🚀 포스트 단일 조회 API 구현
  src/main/java/team/silvertown/masil/post/controller/PostController.java
  src/main/java/team/silvertown/masil/post/domain/Post.java
  src/main/java/team/silvertown/masil/post/domain/PostPin.java
  src/main/java/team/silvertown/masil/post/dto/response/PinResponse.java
  src/main/java/team/silvertown/masil/post/dto/response/PostResponse.java
  src/main/java/team/silvertown/masil/post/exception/PostErrorCode.java
  src/main/java/team/silvertown/masil/post/service/PostService.java
  src/test/java/team/silvertown/masil/post/service/PostServiceTest.java
  src/test/java/team/silvertown/masil/texture/PostTexture.java
Labels: 🐕 진도개 하나!, ✅ Feature

#61 ⚙️ 마실 변경사항 리팩토링
  src/main/java/team/silvertown/masil/masil/domain/Masil.java
  src/main/java/team/silvertown/masil/masil/domain/MasilTitle.java
  src/main/java/team/silvertown/masil/masil/dto/MasilDailyDetailDto.java
  src/main/java/team/silvertown/masil/masil/dto/request/CreateRequest.java
  src/main/java/team/silvertown/masil/masil/dto/response/MasilResponse.java
  src/main/java/team/silvertown/masil/masil/dto/response/PeriodResponse.java
  src/main/java/team/silvertown/masil/masil/exception/MasilErrorCode.java
  src/main/java/team/silvertown/masil/masil/repository/MasilQueryRepositoryImpl.java
  src/main/java/team/silvertown/masil/masil/service/MasilService.java
  src/main/java/team/silvertown/masil/masil/validator/MasilValidator.java
  src/main/resources/db/migration/V1__schema.sql
  src/test/java/team/silvertown/masil/masil/domain/MasilTest.java
  src/test/java/team/silvertown/masil/masil/domain/MasilTitleTest.java
  src/test/java/team/silvertown/masil/masil/service/MasilServiceTest.java
  src/test/java/team/silvertown/masil/texture/MasilTexture.java
Labels: ⚙️ Refactoring, 🐕 진도개 하나!

#71 🚀 스웨거 인증/인가 추가
  build.gradle
  src/main/java/team/silvertown/masil/MasilApplication.java
  src/main/java/team/silvertown/masil/config/SwaggerConfig.java
  src/main/java/team/silvertown/masil/config/security/HttpRequestsConfigurer.java
  src/main/java/team/silvertown/masil/user/controller/UserController.java
  src/main/java/team/silvertown/masil/user/dto/LoginRequest.java
  src/main/java/team/silvertown/masil/user/service/restTemplate/RestTemplateService.java
  src/test/java/team/silvertown/masil/config/jwt/JwtTokenProviderTest.java
  src/test/java/team/silvertown/masil/testConfig/OAuth2TestConfig.java
Labels: 🐕 진도개 하나!, ✅ Feature

#75 fix: 이미 존재하는 회원은 userId 가져온 후 토큰 생성하는 로직으로 변경
  src/main/java/team/silvertown/masil/user/service/UserService.java
Labels: ⚙️ Refactoring, 🐕 진도개 하나!

#79 🔥 이미지 파일 확장자 누락 오류 수정
  src/main/java/team/silvertown/masil/image/service/ImageService.java
Labels: 🔥 Hot fix, 🐛 Bug, 💣 전시 상황!!!

#68 🚀 유저 공개/비공개 여부 변경 api 작성
  src/main/java/team/silvertown/masil/config/WebMvcConfig.java
  src/main/java/team/silvertown/masil/image/service/ImageService.java
  src/main/java/team/silvertown/masil/masil/domain/Masil.java
  src/main/java/team/silvertown/masil/post/domain/Post.java
  src/main/java/team/silvertown/masil/user/controller/UserController.java
  src/main/java/team/silvertown/masil/user/domain/User.java
  src/main/java/team/silvertown/masil/user/dto/MeInfoResponse.java
  src/main/java/team/silvertown/masil/user/service/UserService.java
  src/test/java/team/silvertown/masil/image/service/ImageServiceTest.java
  src/test/java/team/silvertown/masil/test/LocalstackTest.java
  src/test/java/team/silvertown/masil/user/service/UserServiceTest.java
Labels: ⚙️ Refactoring, 🐕🐕🐕 진도개 셋!, ✅ Feature

#70 🚀 유저 정보 업데이트 api 작성
  src/main/java/team/silvertown/masil/user/controller/UserController.java
  src/main/java/team/silvertown/masil/user/domain/User.java
  src/main/java/team/silvertown/masil/user/dto/UpdateRequest.java
  src/main/java/team/silvertown/masil/user/service/UserService.java
  src/test/java/team/silvertown/masil/user/service/UserServiceTest.java
Labels: ⚙️ Refactoring, ✅ Feature

#59 🚀 메이트 엔티티 및 도메인 추가
  src/main/java/team/silvertown/masil/MasilApplication.java
  src/main/java/team/silvertown/masil/mate/domain/Gathering.java
  src/main/java/team/silvertown/masil/mate/domain/Mate.java
  src/main/java/team/silvertown/masil/mate/domain/MateParticipant.java
  src/main/java/team/silvertown/masil/mate/domain/MateStatus.java
  src/main/java/team/silvertown/masil/mate/domain/ParticipantStatus.java
  src/main/java/team/silvertown/masil/mate/exception/MateErrorCode.java
  src/main/java/team/silvertown/masil/mate/validator/MateValidator.java
  src/main/resources/db/migration/V1__initial_schema.sql
  src/main/resources/db/migration/V1__schema.sql
  src/main/resources/db/migration/V2__schema.sql
  src/test/java/team/silvertown/masil/config/JwtTestConfig.java
  src/test/java/team/silvertown/masil/mate/domain/GatheringTest.java
  src/test/java/team/silvertown/masil/mate/domain/MateParticipantTest.java
  src/test/java/team/silvertown/masil/mate/domain/MateTest.java
  src/test/java/team/silvertown/masil/mate/domain/ParticipantStatusTest.java
  src/test/java/team/silvertown/masil/texture/MateTexture.java
Labels: 🐕🐕🐕 진도개 셋!, ✅ Feature

#88 📚 image api swagger 적용
  src/main/java/team/silvertown/masil/image/controller/ImageController.java
  src/main/java/team/silvertown/masil/image/exception/ImageErrorCode.java
Labels: 📄 Docs, 🐕🐕🐕 진도개 셋!

#89 🔥 Front-end service origin CORS 설정
  src/main/java/team/silvertown/masil/config/CORSProperties.java
  src/main/java/team/silvertown/masil/config/WebMvcConfig.java
  src/main/resources/application.yml
Labels: 🔥 Hot fix, 🐕 진도개 하나!, 🐛 Bug

#80 🚀 산책로 포스트 목록 조회 API 구현
  src/main/java/team/silvertown/masil/common/response/ScrollResponse.java
  src/main/java/team/silvertown/masil/common/response/SliceResponse.java
  src/main/java/team/silvertown/masil/config/SwaggerConfig.java
  src/main/java/team/silvertown/masil/config/WebMvcConfig.java
  src/main/java/team/silvertown/masil/config/security/HttpRequestsConfigurer.java
  src/main/java/team/silvertown/masil/masil/controller/MasilController.java
  src/main/java/team/silvertown/masil/masil/dto/request/CreateMasilPinRequest.java
  src/main/java/team/silvertown/masil/masil/dto/request/CreateMasilRequest.java
  src/main/java/team/silvertown/masil/masil/dto/response/CreateMasilResponse.java
  src/main/java/team/silvertown/masil/masil/dto/response/MasilDetailResponse.java
  src/main/java/team/silvertown/masil/masil/dto/response/MasilPinDetailResponse.java
  src/main/java/team/silvertown/masil/masil/service/MasilService.java
  src/main/java/team/silvertown/masil/post/controller/PostController.java
  src/main/java/team/silvertown/masil/post/dto/PostCursorDto.java
  src/main/java/team/silvertown/masil/post/dto/request/CreatePostPinRequest.java
  src/main/java/team/silvertown/masil/post/dto/request/CreatePostRequest.java
  src/main/java/team/silvertown/masil/post/dto/request/NormalListRequest.java
  src/main/java/team/silvertown/masil/post/dto/request/PostOrderType.java
  src/main/java/team/silvertown/masil/post/dto/response/CreatePostResponse.java
  src/main/java/team/silvertown/masil/post/dto/response/PostDetailResponse.java
  src/main/java/team/silvertown/masil/post/dto/response/PostPinDetailResponse.java
  src/main/java/team/silvertown/masil/post/dto/response/SimplePostResponse.java
  src/main/java/team/silvertown/masil/post/exception/PostErrorCode.java
  src/main/java/team/silvertown/masil/post/repository/PostQueryRepository.java
  src/main/java/team/silvertown/masil/post/repository/PostQueryRepositoryImpl.java
  src/main/java/team/silvertown/masil/post/repository/PostRepository.java
  src/main/java/team/silvertown/masil/post/service/PostService.java
  src/main/java/team/silvertown/masil/post/validator/PostValidator.java
  src/test/java/team/silvertown/masil/masil/service/MasilServiceTest.java
  src/test/java/team/silvertown/masil/post/service/PostServiceTest.java
  src/test/java/team/silvertown/masil/texture/PostTexture.java
Labels: 🐕🐕 진도개 둘!, ✅ Feature

#85 🚀 마실 생성 시 사용자 통계 갱신
  src/main/java/team/silvertown/masil/masil/domain/Masil.java
  src/main/java/team/silvertown/masil/masil/dto/request/CreateMasilRequest.java
  src/main/java/team/silvertown/masil/user/domain/User.java
  src/main/resources/db/migration/V1__initial_schema.sql
  src/test/java/team/silvertown/masil/masil/domain/MasilTest.java
  src/test/java/team/silvertown/masil/texture/UserTexture.java
  src/test/java/team/silvertown/masil/user/domain/UserTest.java
Labels: 🐕 진도개 하나!, ✅ Feature

#84 🚀 Dev API CD pipeline 구축
  .aws/Dockerfile
  .aws/init-aws.sh
  .aws/masilgasil-ecs-task-revision1.json
  .aws/policy.json
  .github/workflows/cd-pipeline.yml
  Dockerfile
  docker-compose.yml
Labels: ✅ Feature, 💣 전시 상황!!!

#93 🚀 프론트엔드 개발 생산성을 위한 관리자 패널 추가
  .github/workflows/cd-pipeline-dev.yml
  .gitignore
  build.gradle
  src/main/java/team/silvertown/masil/MasilApplication.java
  src/main/java/team/silvertown/masil/config/SnapAdminProperties.java
  src/main/java/team/silvertown/masil/config/security/HttpRequestsConfigurer.java
  src/main/java/team/silvertown/masil/masil/domain/Masil.java
  src/main/java/team/silvertown/masil/masil/domain/MasilPin.java
  src/main/java/team/silvertown/masil/mate/domain/Gathering.java
  src/main/java/team/silvertown/masil/mate/domain/Mate.java
  src/main/java/team/silvertown/masil/mate/domain/MateParticipant.java
  src/main/java/team/silvertown/masil/post/domain/Post.java
  src/main/java/team/silvertown/masil/post/domain/PostPin.java
  src/main/java/team/silvertown/masil/user/domain/User.java
  src/main/java/team/silvertown/masil/user/domain/UserAgreement.java
  src/main/java/team/silvertown/masil/user/domain/UserAuthority.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
Labels: 🐕🐕🐕 진도개 셋!, ✅ Feature

#103 🔥 cd pipeline 에서 profile이 적용되지 않는 오류 수정
  .github/workflows/cd-pipeline-dev.yml
  Dockerfile
  src/main/java/team/silvertown/masil/config/SnapAdminProperties.java
  src/main/java/team/silvertown/masil/config/security/HttpRequestsConfigurer.java
  src/test/resources/application-dev.yml
Labels: 🔥 Hot fix, 🐕🐕 진도개 둘!, 🐛 Bug

#92 🚀 유저 프로필 사진 수정 api
  src/main/java/team/silvertown/masil/config/WebMvcConfig.java
  src/main/java/team/silvertown/masil/image/exception/ImageErrorCode.java
  src/main/java/team/silvertown/masil/image/validator/ImageFileServiceValidator.java
  src/main/java/team/silvertown/masil/masil/domain/Masil.java
  src/main/java/team/silvertown/masil/user/controller/UserController.java
  src/main/java/team/silvertown/masil/user/domain/User.java
  src/main/java/team/silvertown/masil/user/dto/NicknameCheckResponse.java
  src/main/java/team/silvertown/masil/user/exception/UserErrorCode.java
  src/main/java/team/silvertown/masil/user/repository/UserAgreementRepository.java
  src/main/java/team/silvertown/masil/user/service/UserService.java
  src/test/java/team/silvertown/masil/user/service/UserServiceTest.java
Labels: ✅ Feature

#99 🚀 mypage 호출 api 작성
  src/main/java/team/silvertown/masil/config/security/HttpRequestsConfigurer.java
  src/main/java/team/silvertown/masil/user/controller/UserController.java
  src/main/java/team/silvertown/masil/user/dto/MyPageInfoResponse.java
  src/main/java/team/silvertown/masil/user/service/UserService.java
  src/test/java/team/silvertown/masil/texture/UserAuthorityTexture.java
  src/test/java/team/silvertown/masil/texture/UserTexture.java
  src/test/java/team/silvertown/masil/user/service/UserServiceTest.java
Labels: ✅ Feature

#106 ⚙️ enum 값들을 가지는 경우 값을 포함하지 않은 경우 업데이트 하지 않게 만들기
  src/main/java/team/silvertown/masil/user/domain/ExerciseIntensity.java
  src/main/java/team/silvertown/masil/user/domain/Sex.java
  src/main/java/team/silvertown/masil/user/domain/User.java
  src/main/java/team/silvertown/masil/user/service/UserService.java
  src/test/java/team/silvertown/masil/user/service/UserServiceTest.java
Labels: ⚙️ Refactoring, 🐛 Bug

#97 🚀 메이트 모집 생성 API 구현
  src/main/java/team/silvertown/masil/masil/repository/MasilQueryRepositoryImpl.java
  src/main/java/team/silvertown/masil/mate/controller/MateController.java
  src/main/java/team/silvertown/masil/mate/domain/MateParticipant.java
  src/main/java/team/silvertown/masil/mate/dto/request/CreateMateRequest.java
  src/main/java/team/silvertown/masil/mate/dto/response/CreateMateResponse.java
  src/main/java/team/silvertown/masil/mate/exception/MateErrorCode.java
  src/main/java/team/silvertown/masil/mate/repository/MateParticipantQueryRepository.java
  src/main/java/team/silvertown/masil/mate/repository/MateParticipantQueryRepositoryImpl.java
  src/main/java/team/silvertown/masil/mate/repository/MateParticipantRepository.java
  src/main/java/team/silvertown/masil/mate/repository/MateRepository.java
  src/main/java/team/silvertown/masil/mate/service/MateService.java
  src/test/java/team/silvertown/masil/mate/service/MateServiceTest.java
  src/test/java/team/silvertown/masil/texture/MapTexture.java
  src/test/java/team/silvertown/masil/texture/MateTexture.java
Labels: ✅ Feature, 💣 전시 상황!!!

#115 🚀 환경 별 스웨거 설정 추가
  .github/workflows/cd-pipeline-dev.yml
  src/main/java/team/silvertown/masil/config/SwaggerConfig.java
  src/main/java/team/silvertown/masil/post/controller/PostController.java
  src/main/resources/application.yml
Labels: ✅ Feature, 💣 전시 상황!!!

#125 🐛 스웨거로 로그인 시 잘못된 설정 수정
  src/main/java/team/silvertown/masil/user/controller/UserController.java
Labels: 🐛 Bug

#124 🐛 목록 조회 시 사이즈가 없으면 실패하는 버그 수정
  src/main/java/team/silvertown/masil/common/scroll/dto/NormalListRequest.java
  src/main/java/team/silvertown/masil/common/scroll/dto/ScrollRequest.java
Labels: 🐕🐕 진도개 둘!, 🐛 Bug

#112 🚀 포스트 조회수 증가 기능 추가
  .github/workflows/cd-pipeline-dev.yml
  .github/workflows/ci-pipeline.yml
  build.gradle
  docker-compose.yml
  src/main/java/team/silvertown/masil/image/controller/ImageController.java
  src/main/java/team/silvertown/masil/post/domain/Post.java
  src/main/java/team/silvertown/masil/post/domain/PostViewHistory.java
  src/main/java/team/silvertown/masil/post/exception/PostErrorCode.java
  src/main/java/team/silvertown/masil/post/repository/PostViewHistoryRepository.java
  src/main/java/team/silvertown/masil/post/service/PostService.java
  src/main/java/team/silvertown/masil/post/validator/PostViewHistoryValidator.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/java/team/silvertown/masil/post/domain/PostViewHistoryTest.java
  src/test/java/team/silvertown/masil/post/service/PostServiceTest.java
  src/test/resources/application.yml
Labels: 🐕🐕 진도개 둘!, ✅ Feature

#121 ⚙️ CD pipeline 환경 변수 설정
  .aws/masilgasil-ecs-task-dev-revision1.json
  .github/workflows/cd-pipeline.yml
Labels: ⚙️ Refactoring, 🐕 진도개 하나!

#132 🚀 배포 환경 별 파이프라인 스크립트 분리
  .aws/masilgasil-ecs-task-prod-revision1.json
  .github/workflows/cd-pipeline-dev.yml
  .github/workflows/cd-pipeline-prod.yml
Labels: ✅ Feature

#138 🚀 API 서버 모니터링 서비스 Centry 적용
  .github/workflows/cd-pipeline-dev.yml
  build.gradle
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: ✅ Feature, 💣 전시 상황!!!

#120 🚀 메이트 모집 참여 요청 API 구현
  src/main/java/team/silvertown/masil/mate/controller/MateParticipantController.java
  src/main/java/team/silvertown/masil/mate/domain/MateParticipant.java
  src/main/java/team/silvertown/masil/mate/domain/ParticipantStatus.java
  src/main/java/team/silvertown/masil/mate/dto/request/CreateMateParticipantRequest.java
  src/main/java/team/silvertown/masil/mate/dto/response/CreateMateParticipantResponse.java
  src/main/java/team/silvertown/masil/mate/exception/MateErrorCode.java
  src/main/java/team/silvertown/masil/mate/service/MateService.java
  src/main/java/team/silvertown/masil/mate/validator/MateValidator.java
  src/test/java/team/silvertown/masil/mate/domain/MateParticipantTest.java
  src/test/java/team/silvertown/masil/mate/domain/ParticipantStatusTest.java
  src/test/java/team/silvertown/masil/mate/service/MateServiceTest.java
  src/test/java/team/silvertown/masil/texture/MateTexture.java
Labels: 🐕 진도개 하나!, ✅ Feature

#135 🚀 메이트 상세조회 시 참여자 사용자 id와 포스트 id 추가
  src/main/java/team/silvertown/masil/mate/dto/response/MateDetailResponse.java
  src/main/java/team/silvertown/masil/mate/dto/response/ParticipantResponse.java
Labels: ✅ Feature

#140 🚀 메이트 조회 시 상태 변경 추가
  src/main/java/team/silvertown/masil/mate/domain/Mate.java
  src/main/java/team/silvertown/masil/mate/dto/MateCursorDto.java
  src/main/java/team/silvertown/masil/mate/dto/response/MateDetailResponse.java
  src/main/java/team/silvertown/masil/mate/dto/response/SimpleMateResponse.java
  src/main/java/team/silvertown/masil/mate/repository/mate/MateQueryRepositoryImpl.java
  src/main/java/team/silvertown/masil/mate/service/MateService.java
Labels: ✅ Feature, 💣 전시 상황!!!

#136 🚀 로그인에 refresh token 기능 적용
  .github/workflows/cd-pipeline-dev.yml
  .github/workflows/cd-pipeline-prod.yml
  src/main/java/team/silvertown/masil/auth/controller/AuthController.java
  src/main/java/team/silvertown/masil/auth/domain/RefreshToken.java
  src/main/java/team/silvertown/masil/auth/dto/LoginResponse.java
  src/main/java/team/silvertown/masil/auth/exception/AuthErrorCode.java
  src/main/java/team/silvertown/masil/auth/jwt/JwtProperties.java
  src/main/java/team/silvertown/masil/auth/jwt/JwtTokenProvider.java
  src/main/java/team/silvertown/masil/auth/repository/RefreshTokenRepository.java
  src/main/java/team/silvertown/masil/auth/service/AuthService.java
  src/main/java/team/silvertown/masil/auth/service/KakaoOAuthService.java
  src/main/java/team/silvertown/masil/auth/service/OAuthService.java
  src/main/java/team/silvertown/masil/config/SwaggerConfig.java
  src/main/java/team/silvertown/masil/config/security/CustomAuthenticationEntryPoint.java
  src/main/java/team/silvertown/masil/config/security/HttpRequestsConfigurer.java
  src/main/java/team/silvertown/masil/config/security/JwtAuthenticationFilter.java
  src/main/java/team/silvertown/masil/config/security/WebSecurityConfig.java
  src/main/java/team/silvertown/masil/user/controller/UserController.java
  src/main/java/team/silvertown/masil/user/domain/Provider.java
  src/main/java/team/silvertown/masil/user/domain/User.java
  src/main/java/team/silvertown/masil/user/dto/LoginResponse.java
  src/main/java/team/silvertown/masil/user/dto/OAuthResponse.java
  src/main/java/team/silvertown/masil/user/exception/UserErrorCode.java
  src/main/java/team/silvertown/masil/user/exception/UserValidator.java
  src/main/java/team/silvertown/masil/user/service/KakaoOAuthService.java
  src/main/java/team/silvertown/masil/user/service/UserService.java
  src/main/resources/application.yml
  src/test/java/team/silvertown/masil/config/JwtTestConfig.java
  src/test/java/team/silvertown/masil/config/jwt/JwtTokenProviderTest.java
  src/test/java/team/silvertown/masil/user/domain/ProviderTest.java
  src/test/java/team/silvertown/masil/user/service/KakaoOAuthServiceTest.java
  src/test/java/team/silvertown/masil/user/service/UserServiceTest.java
Labels: ✅ Feature, 💣 전시 상황!!!

#141 🚀 메이트 참여자 신청 수락 API 구현
  src/main/java/team/silvertown/masil/mate/controller/MateParticipantController.java
  src/main/java/team/silvertown/masil/mate/domain/MateParticipant.java
  src/main/java/team/silvertown/masil/mate/exception/MateErrorCode.java
  src/main/java/team/silvertown/masil/mate/repository/participant/MateParticipantQueryRepository.java
  src/main/java/team/silvertown/masil/mate/repository/participant/MateParticipantQueryRepositoryImpl.java
  src/main/java/team/silvertown/masil/mate/service/MateService.java
  src/main/java/team/silvertown/masil/mate/validator/MateValidator.java
  src/test/java/team/silvertown/masil/mate/service/MateServiceTest.java
  src/test/resources/application.yml
Labels: ✅ Feature, 💣 전시 상황!!!

#142 🚀 메이트 참여 삭제 API 구현
  src/main/java/team/silvertown/masil/mate/controller/MateParticipantController.java
  src/main/java/team/silvertown/masil/mate/service/MateService.java
  src/main/java/team/silvertown/masil/mate/validator/MateValidator.java
  src/test/java/team/silvertown/masil/mate/service/MateServiceTest.java
Labels: ✅ Feature, 💣 전시 상황!!!

#144 🚀 메이트 상세 조회 시 작성자면 참여자들 요청 메세지 조회
  src/main/java/team/silvertown/masil/mate/controller/MateController.java
  src/main/java/team/silvertown/masil/mate/dto/response/ParticipantResponse.java
  src/main/java/team/silvertown/masil/mate/service/MateService.java
  src/test/java/team/silvertown/masil/mate/service/MateServiceTest.java
Labels: ✅ Feature, 💣 전시 상황!!!

#149 🚀 dev 서버 기능 추가
  .github/workflows/cd-pipeline-dev.yml
  .github/workflows/cd-pipeline-prod.yml
  src/main/java/team/silvertown/masil/auth/controller/AuthController.java
  src/main/java/team/silvertown/masil/auth/domain/RefreshToken.java
  src/main/java/team/silvertown/masil/auth/dto/LoginResponse.java
  src/main/java/team/silvertown/masil/auth/exception/AuthErrorCode.java
  src/main/java/team/silvertown/masil/auth/jwt/JwtProperties.java
  src/main/java/team/silvertown/masil/auth/jwt/JwtTokenProvider.java
  src/main/java/team/silvertown/masil/auth/repository/RefreshTokenRepository.java
  src/main/java/team/silvertown/masil/auth/service/AuthService.java
  src/main/java/team/silvertown/masil/auth/service/KakaoOAuthService.java
  src/main/java/team/silvertown/masil/auth/service/OAuthService.java
  src/main/java/team/silvertown/masil/config/SwaggerConfig.java
  src/main/java/team/silvertown/masil/config/security/CustomAuthenticationEntryPoint.java
  src/main/java/team/silvertown/masil/config/security/HttpRequestsConfigurer.java
  src/main/java/team/silvertown/masil/config/security/JwtAuthenticationFilter.java
  src/main/java/team/silvertown/masil/config/security/WebSecurityConfig.java
  src/main/java/team/silvertown/masil/mate/controller/MateController.java
  src/main/java/team/silvertown/masil/mate/controller/MateParticipantController.java
  src/main/java/team/silvertown/masil/mate/domain/MateParticipant.java
  src/main/java/team/silvertown/masil/mate/dto/response/ParticipantResponse.java
  src/main/java/team/silvertown/masil/mate/exception/MateErrorCode.java
  src/main/java/team/silvertown/masil/mate/repository/participant/MateParticipantQueryRepository.java
  src/main/java/team/silvertown/masil/mate/repository/participant/MateParticipantQueryRepositoryImpl.java
  src/main/java/team/silvertown/masil/mate/service/MateService.java
  src/main/java/team/silvertown/masil/mate/validator/MateValidator.java
  src/main/java/team/silvertown/masil/user/controller/UserController.java
  src/main/java/team/silvertown/masil/user/domain/Provider.java
  src/main/java/team/silvertown/masil/user/domain/User.java
  src/main/java/team/silvertown/masil/user/dto/LoginResponse.java
  src/main/java/team/silvertown/masil/user/dto/OAuthResponse.java
  src/main/java/team/silvertown/masil/user/exception/UserErrorCode.java
  src/main/java/team/silvertown/masil/user/exception/UserValidator.java
  src/main/java/team/silvertown/masil/user/service/KakaoOAuthService.java
  src/main/java/team/silvertown/masil/user/service/UserService.java
  src/main/resources/application.yml
  src/test/java/team/silvertown/masil/config/JwtTestConfig.java
  src/test/java/team/silvertown/masil/config/jwt/JwtTokenProviderTest.java
  src/test/java/team/silvertown/masil/mate/service/MateServiceTest.java
  src/test/java/team/silvertown/masil/user/domain/ProviderTest.java
  src/test/java/team/silvertown/masil/user/service/KakaoOAuthServiceTest.java
  src/test/java/team/silvertown/masil/user/service/UserServiceTest.java
  src/test/resources/application.yml
Labels: ✅ Feature

#154 ⚙️ CI 과정 중 유저 닉네임 예외 발생 가능성 제거
  src/test/java/team/silvertown/masil/texture/UserTexture.java
Labels: ⚙️ Refactoring

#146 🚀 산책로 (Post) 좋아요 기능 추가
  src/main/java/team/silvertown/masil/post/controller/PostLikeController.java
  src/main/java/team/silvertown/masil/post/domain/Post.java
  src/main/java/team/silvertown/masil/post/domain/PostLike.java
  src/main/java/team/silvertown/masil/post/domain/PostLikeId.java
  src/main/java/team/silvertown/masil/post/dto/SaveLikeDto.java
  src/main/java/team/silvertown/masil/post/exception/PostErrorCode.java
  src/main/java/team/silvertown/masil/post/repository/PostLikeRepository.java
  src/main/java/team/silvertown/masil/post/service/PostLikeService.java
  src/main/resources/db/migration/V2__create_post_likes_table.sql
  src/test/java/team/silvertown/masil/post/service/PostLikeServiceTest.java
Labels: ✅ Feature, 💣 전시 상황!!!

#153 🐛 메이트 작성자가 상세 조회 시 참여자의 메세지가 null로 뜨는 버그 수정
  src/main/java/team/silvertown/masil/mate/controller/MateController.java
  src/main/java/team/silvertown/masil/mate/dto/response/ParticipantResponse.java
  src/main/java/team/silvertown/masil/post/controller/PostController.java
  src/test/java/team/silvertown/masil/mate/service/MateServiceTest.java
Labels: 🐛 Bug, 💣 전시 상황!!!

#148 ⚙️ user 가입 시 통계자료 모두 0으로 초기화
  src/main/java/team/silvertown/masil/user/service/UserService.java
Labels: ⚙️ Refactoring, 💣 전시 상황!!!

#159 🚀 산책로 포스트 조회 시 좋아요 여부 표시 추가
  src/main/java/team/silvertown/masil/post/controller/PostController.java
  src/main/java/team/silvertown/masil/post/controller/PostLikeController.java
  src/main/java/team/silvertown/masil/post/dto/response/PostDetailResponse.java
  src/main/java/team/silvertown/masil/post/dto/response/SimplePostResponse.java
  src/main/java/team/silvertown/masil/post/repository/PostQueryRepositoryImpl.java
  src/main/java/team/silvertown/masil/post/service/PostService.java
  src/test/java/team/silvertown/masil/post/service/PostServiceTest.java
Labels: 🐕 진도개 하나!, ✅ Feature

#161 🐛 포스트 단일 조회 시 좋아요 잘못 나오는 버그 수정
  src/main/java/team/silvertown/masil/post/dto/response/SimplePostResponse.java
  src/main/java/team/silvertown/masil/post/service/PostService.java
Labels: 🐛 Bug
